[colors.bright]
black = "0x2a2a33"
blue = "0x8cc7de"
cyan = "0x35d4d4"
green = "0xa3e28f"
magenta = "0xe89ec0"
red = "0xff6b81"
white = "0xf5f5ee"
yellow = "0xe6d13d"

[colors.cursor]
cursor = "0xd9bd08"
text = "0x0a0a0e"

[colors.dim]
black = "0x0d0d11"
blue = "0x3c6b80"
cyan = "0x009a9f"
green = "0x52814a"
magenta = "0x844765"
red = "0x99243a"
white = "0x8a8a82"
yellow = "0x998c07"

[colors.normal]
black = "0x121218"
blue = "0x5aa7c4"
cyan = "0x00b3c8"
green = "0x7fc96b"
magenta = "0xd6669c"
red = "0xff3352"
white = "0xd6d6cd"
yellow = "0xd9bd08"

[colors.primary]
background = "0x0a0a0e"
foreground = "0xd6d6cd"

[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"

[terminal]
shell = { program = "/bin/zsh", args = ["--login", "-i"] }
osc52 = "CopyPaste"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0


[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"


[mouse]
    hide_when_typing = true
    
    [scrolling]
history = 10000
multiplier = 3

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.95
startup_mode = "Windowed"

[window.padding]
x = 10
y = 10
